### ISSUE TITLE
Unable to build 2025.04 on Alpine Linux

### ISSUE THREAD

**Issue by m-dango** [rakudo/rakudo#5864]
I'm attempting to publish the official Docker images for Rakudo Star, but there seems to be a problem with building Rakudo 2025.04 on Alpine Linux 3.21.

Using `apk add gcc git libc-dev make perl` and `perl Configure.pl --backend=moar --gen-moar` on the releases from rakudo.org, I am able to complete the build on 2025.03, but on 2025.04 I get the following error:

```
compiling 3rdparty/mimalloc/src/static.o
In file included from 3rdparty/mimalloc/src/prim/prim.c:25,
                 from 3rdparty/mimalloc/src/static.c:38:
3rdparty/mimalloc/src/prim/unix/prim.c:34:12: fatal error: linux/prctl.h: No such file or directory
   34 |   #include <linux/prctl.h>  // PR_SET_VMA
      |            ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:674: 3rdparty/mimalloc/src/static.o] Error 1

```

I have attempted `apk add linux-headers`, however this results in a different problem:

```
compiling 3rdparty/mimalloc/src/static.o
In file included from 3rdparty/mimalloc/src/prim/unix/prim.c:36,
                 from 3rdparty/mimalloc/src/prim/prim.c:25,
                 from 3rdparty/mimalloc/src/static.c:38:
/usr/include/sys/prctl.h:88:8: error: redefinition of 'struct prctl_mm_map'
   88 | struct prctl_mm_map {
      |        ^~~~~~~~~~~~
In file included from 3rdparty/mimalloc/src/prim/unix/prim.c:34:
/usr/include/linux/prctl.h:134:8: note: originally defined here
  134 | struct prctl_mm_map {
      |        ^~~~~~~~~~~~
make: *** [Makefile:674: 3rdparty/mimalloc/src/static.o] Error 1
```

Is there something I am missing?

**Comment by m-dango** [comment]
Possibly related issue: https://github.com/microsoft/mimalloc/issues/1056

**Comment by m-dango** [comment]
I've created an issue in MoarVM as that looks to be the cause of the failure: https://github.com/MoarVM/MoarVM/issues/1935

**Comment by melezhik** [comment]
Yep , the last commit build is good as well - https://sparky.sparrowhub.io/report/rakudo-head/24947
